### ISSUE TITLE
How to test this code?

### ISSUE THREAD

**Issue by shootdaj** [GeorgeHahn/espopc2#1]
I am running your code on my NodeMCU, but the program I've been using to test all other implementations doesn't seem to be working probably because it's designed to work over TCP. Here's the program I've been using : https://github.com/scanlime/fadecandy/tree/master/examples/processing/grid8x8_dot

This program works with the original code you forked from, by the way.

Can you suggest how to communicate over sockets with NodeMCU once your code is running?

Sorry, I'm not very well versed in socket programming. I'm currently using C# to write a sample application to light up an LED strip connected to D4. Again, this works for the original code so I think it has something to do with UDP.

**Comment by shootdaj** [comment]
After a few more hours of trial and error, I finally got it to work. In case anyone here is interested, this is the code I used:

`static void Main(string[] args)
        {
            Socket soc = new Socket(AddressFamily.InterNetwork, SocketType.Dgram, ProtocolType.Udp);
            System.Net.IPAddress ipAdd = System.Net.IPAddress.Parse("192.168.29.113");
            System.Net.IPEndPoint remoteEP = new IPEndPoint(ipAdd, 7890);
            soc.Connect(remoteEP);

            byte[] data = new byte[16];
            data[0] = 0x00;
            data[1] = 0x00;
            data[2] = 0x00;
            data[3] = 0x0C;

            for (int i = 0; i < 12; i++)
            {
                data[i + 4] = 0xFF;
            }
            
            soc.Send(data);

            Console.ReadLine();
        }`


There is one issue that I'm experiencing so far. The lights only light up every second time I run the code. The first time, nothing happens. Here is the output from your program:

`Received 16 bytes from 192.168.29.187, port 65100
N
D
.
0:2666640:1:16896
0
80970548
16
 
Received 16 bytes from 192.168.29.187, port 57509
N
D
.
1:2666640:1:16896
0
32034566
16
 
Received 16 bytes from 192.168.29.187, port 56444
N
D
.
2:2666640:1:16896
0
19067382
16
 
Received 16 bytes from 192.168.29.187, port 56445
N
D
.
3:2666640:1:16896
0
9867018
16
 
Received 16 bytes from 192.168.29.187, port 56446
N
D
.
4:2666640:1:16896
0
11967091
16
 
Received 16 bytes from 192.168.29.187, port 52916
N
D
.
5:2666640:1:16896
0
7900255
`

Do you have any idea why I might have to run the code twice? In the TCP version, it works on the first try. Maybe something I'm doing wrong?

**Comment by GeorgeHahn** [comment]
That's the buffering issue I mentioned. Unfortunately, I haven't had the time to track it down yet. Feel free to make another issue for it.

Other nice improvements:
- Playback at average framerate but ignore long gaps ([here](https://github.com/GeorgeHahn/espopc2/blob/master/espopc2.ino#L292))
- Reduce number of buffers ([here](https://github.com/GeorgeHahn/espopc2/blob/master/espopc2.ino#L49))
- General code cleaning (defines, macros, style, etc)
- Add a README file

**Comment by shootdaj** [comment]
I will close this since you started another issue for the example code etc.
